#Introduction to Python

"""
This notebook is designed to give you an introduction to how to write a simple piece of Python code.
Show you the environment in which Python can work and describe the basic data structures.

This is a iPython Notebook, one of the ways in which you can write run and save python code.  The
notebook runs within a browser, but relies on an underlying installation of Python.  For those interested
in running python on their machines the simplest way to install python is to use one of the precompiled 
packages availabale online.  I recommend using enthought, which is free for those with a .ac.uk email
address https://www.enthought.com/products/canopy/ .  There are multiple versions of python, use
the latest version unless you have a specific reason to do otherwise, e.g. compatability with other
software.

Alternatively, there are now options available where instances of python can be run in chrome for example
without the need for installation e.g. https://chrome.google.com/webstore/detail/colaboratory-notebook/

The former of these allows you to incorporate a number of packages with different capabilities.
The latter has a limited number of packages.

To start an ipython notebook open a terminal/command prompt and type ipython notebook........
This should open your browser.

To run code or get a new line after entering comments use shift+enter
cells can be change to markdown or code using the cell dropdown menu above
"""

In [2]:
# comments can be enrted between triple speech marks as above or after the has symbol as here
# The first step with any python code is to import the necessary modules, which contain the 
# code necesarry for further steps
"""
Comments
"""

In [23]:
# In this case a few cor modules are necessary
import numpy
import datetime

# Series/ lists and indexing

In [24]:
myList = [1,2,3,4,5,6,7,8]

In [27]:
# lists can be accessed in a number of ways, e.g. selecting the first value (0 is the first value in python)
myList[3]

4

In [28]:
# selecting the first the third value
myList[0:3]

[1, 2, 3]

In [30]:
# indexing can also be used without inserting numbers, e.g.
myList[:3]

[1, 2, 3]

In [31]:
# or
myList[3:]

[4, 5, 6, 7, 8]

# Arrays

In [32]:
# Lists or series are only one dimensional, in order to add more dimnesions, or functionaity, use and array
myArray = numpy.array([[1,2,3,4],[5,6,7,8]])

In [33]:

myArray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
myArray[0]

array([1, 2, 3, 4])

In [35]:
myArray[1]


array([5, 6, 7, 8])

In [36]:
# witht the added dimnesion you can now index columns
myArray[:,2]

array([3, 7])

In [37]:
# or
myArray[:,0:2]

array([[1, 2],
       [5, 6]])

In [ ]:
# Structured arrays allow you to index by column name references, I will skip these, but llok online for 
# more information

# Operations on arrays and lists

In [60]:
# you can add to, remove from or apply eqautions to arrays

In [41]:
# e.g. append
myList.append([9,10,11])

In [42]:
myList

[1, 2, 3, 4, 5, 6, 7, 8, 9, [9, 10, 11]]

In [45]:
# append does not work on arrays, but you can stack another array
numpy.vstack([myArray,[9,10,11,12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
# or concatenate, beware that in all these cases dimensions and syntax matter, particulalry with brackets
numpy.concatenate([myArray,[[9,10,11,12],[13,14,15,16]]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [48]:
# Mathematical operations are simple to apply to arrays and list, but work in different ways e.g.
myList*2

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 [9, 10, 11],
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 [9, 10, 11]]

In [49]:
myArray*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [50]:
myArray*myArray

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

# datatypes

In [51]:
# so far only integeres have been shown, but all data containers can also be filled with
# floats - 
floatList = [1.0,2.0,3.5,4.3,5.6]

In [52]:
floatList

[1.0, 2.0, 3.5, 4.3, 5.6]

In [53]:
#be careful when using a mix of floats and integers , e.g.
1/2

0

In [54]:
1/2.0

0.5

In [56]:
# and characters
charList = ['A','B','C','D']

In [57]:
charList

['A', 'B', 'C', 'D']

#Dictionaries

In [58]:
# Data can also be stored as dictionaries
# here data is stored as a key with an associated value, either can be used for access
# any of the above datatypes can be mixed, curly parenthesese are used to decalre the dictionary
myDict = {'Array': myArray, 'List': myList, 1:12}

In [59]:
# to show the keys
myDict.keys()

[1, 'Array', 'List']

In [60]:
# to show the values 
myDict.values()

[12, array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), [1, 2, 3, 4, 5, 6, 7, 8, 9, [9, 10, 11]]]

In [62]:
# to call by key
myDict['Array']

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Dates and times

In [63]:
# Date and time are pretty important when modelling electricity demand and supply
# I will go thorugh these in detail in the following case studies, for now it is important to know
# that the datetime module can be importd
import datetime

In [64]:
# and this is the format (now is used as and example and shows time now)
# year, month, day, hour, minutes, seconds, fractions of a second
datetime.datetime.now()

datetime.datetime(2016, 3, 9, 12, 53, 38, 215000)

In [65]:
# as a string
str(datetime.datetime.now())

'2016-03-09 12:54:02.497000'

In [22]:
# this module can also be used to import date and time in any format - very useful for collecting data.

#Pandas

In [ ]:
# Pandas is an important python module 